chore(integration card): add icon support. design pass on integration…
supaglue-labs/supaglue pull request #122
Opened 2023-02-14 17:44 UTC by tomkit

… card in sample-app

![Screenshot 2023-02-14 at 9 43 16 AM](https://user-images.githubusercontent.com/471516/218816275-426e3598-e5ce-441b-8c6c-d1404c9ccaab.png)

2023-02-14 18:04 UTC, asdfryan commented on apps/sample-app/styles/globals.css
> +.sg-salesforceDisconnectButton {
Isn't this the wrong place to make this change? This should go as a default style

2023-02-14 18:05 UTC, asdfryan requested changes
Can you post a screenshot of what the new card looks like on dark theme? (which is now part of the tutorial)

2023-02-14 21:11 UTC, tomkit commented on apps/sample-app/styles/globals.css
> +.sg-salesforceDisconnectButton {
I think there's not other way to do it now? Is there a way to change the connect and disconnect button outside of stylesheets?

2023-02-14 21:15 UTC, tomkit commented
> Can you post a screenshot of what the new card looks like on dark theme? (which is now part of the tutorial)
<img width="371" alt="Screenshot 2023-02-14 at 1 15 26 PM" src="https://user-images.githubusercontent.com/471516/218864753-7141b4b6-c117-4cb9-8750-70a70ed9b4e2.png">

what's the best way to update the dark theme now ?

2023-02-14 21:27 UTC, asdfryan commented on apps/sample-app/styles/globals.css
> +.sg-salesforceDisconnectButton {
Yes. See all of the `styles.ts` files for all the elements/components/primitives.

2023-02-14 21:28 UTC, lucasmarshall commented on packages/nextjs/src/components/IntegrationCard/IntegrationCard.tsx
> +      {UserIcon ? UserIcon : null}
`UserIcon` defaults to `null`, so the ternary shouldn't be needed.

2023-02-15 01:20 UTC, asdfryan commented on apps/sample-app/pages/index.tsx
> +        {activeTab === 'App Contacts' && <ContactsTable initialUsers={contacts} initialTotalUsers={count} />}
I think this will break the integration since right now we use the tab name to look for the sync config.

2023-02-15 01:21 UTC, tomkit commented on apps/sample-app/pages/index.tsx
> +        {activeTab === 'App Contacts' && <ContactsTable initialUsers={contacts} initialTotalUsers={count} />}
Ok, it's aiming to clarify the app vs sfdc objects. I'll add in a label or something

2023-02-15 03:00 UTC, lucasmarshall approved these changes

2023-02-15 04:03 UTC, merged

2023-02-15 18:16 UTC, asdfryan commented
I think the tabs are broken on the Users page @tomkit