fix: return cache invalidation errors on read or db write errors
supaglue-labs/supaglue pull request #1647
Opened 2023-09-26 20:13 UTC by lucasmarshall

2023-09-26 21:03 UTC, asdfryan requested changes
we also need to update `engagement/common_object_service.ts`

2023-09-26 22:09 UTC, tomkit reviewed
Can we do extra testing for this (positive and negative case) b/c it's in the critical path customers are sensitive to changes here

2023-09-26 22:09 UTC, tomkit commented on packages/core/services/common_objects/crm/common_object_service.ts
> +        throw new CacheInvalidationError(err.message, err);
I think we should throw our own error message, i.e. what we had before so it's clear it's cache invalidation, but log and pass along the remote provider error into the jsonapi "details" field (which we're doing here in the second argument) for developers

2023-09-26 22:09 UTC, tomkit commented on packages/core/destination_writers/mongodb.ts
>        childLogger.error({ err }, 'Error upserting common object record');
In retrospect: we should log an error here so it's clear that the upsert is causing a cache invalidation issue

2023-09-26 22:11 UTC, lucasmarshall commented on packages/core/services/common_objects/crm/common_object_service.ts
> +        throw new CacheInvalidationError(err.message, err);
Isn't it clear it's a cache invalidation error since the error code is `CACHE_INVALIDATION_ERROR`?

2023-09-26 22:12 UTC, lucasmarshall commented on packages/core/destination_writers/mongodb.ts
>        childLogger.error({ err }, 'Error upserting common object record');
We are already logging that here.

2023-09-26 22:13 UTC, lucasmarshall commented
> Can we do extra testing for this (positive and negative case) b/c it's in the critical path and customers are sensitive to changes here

I already did testing here for both cases. What more testing would you like?

2023-09-26 22:18 UTC, tomkit commented on packages/core/destination_writers/mongodb.ts
>        childLogger.error({ err }, 'Error upserting common object record');
I guess the litmus test is: Will we be able to quickly scan Datadog for and differentiate between cache invalidation vs other upsert() errors?

2023-09-26 22:20 UTC, tomkit commented on packages/core/services/common_objects/crm/common_object_service.ts
> +        throw new CacheInvalidationError(err.message, err);
Yes, true. That sgtm

2023-09-26 22:20 UTC, tomkit commented
> > Can we do extra testing for this (positive and negative case) b/c it's in the critical path and customers are sensitive to changes here
> 
> I already did testing here for both cases. What more testing would you like?

Nice - ty. I'm addin extra diligence here b/c there's a large matrix, it's in the critical path, and customers are sensitive. My only check is: can we do both Engagement and CRM tests (if not already)?

2023-09-26 22:35 UTC, lucasmarshall commented on packages/core/destination_writers/mongodb.ts
>        childLogger.error({ err }, 'Error upserting common object record');
Not unless we pass a flag here that says this upsert is for cache invaldation. Is that what we want?

2023-09-26 23:21 UTC, asdfryan requested changes

2023-09-26 23:21 UTC, asdfryan commented on packages/core/services/common_objects/engagement/common_object_service.ts
> +      try {
Unfortunately you also need to update `create()` as well.

It'd be great to refactor this but it's up to you.

2023-09-27 18:39 UTC, asdfryan approved these changes

2023-09-27 18:47 UTC, merged