feat: Sequence integration tests
supaglue-labs/supaglue pull request #1843
Opened 2023-11-02 17:49 UTC by tonyxiao

Fixes: #### 

[Describe your change here]

## Test Plan

[Describe test plan here]

## Deployment instructions

[Add any special deployment instructions here]

2023-11-02 19:18 UTC, asdfryan requested changes
I think we should also test `sequenceState`.

Something new that we decided to commit to was to also test invalid request bodies and test that the error responses include relevant context.

2023-11-02 19:20 UTC, asdfryan commented on packages/core/remotes/impl/salesloft/mappers.ts
> +            step.type === 'auto_email' ? { send_type: 'after_time_delay', delay_time: delayInMins } : undefined,
I think you may have to update the existing mapper unit tests

2023-11-02 19:23 UTC, asdfryan commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +        objectName: 'account',
This doesn't look quite right? It should be `sequence` -- and there should probably be additional cleanup code written in `integration-test-environment.js`

2023-11-02 21:33 UTC, tonyxiao commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +        objectName: 'account',
Thanks for the catch!

2023-11-02 22:41 UTC, tonyxiao commented
Done for both

2023-11-02 23:34 UTC, asdfryan commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +      addedObjects.push({
Does this get cleaned up at the end even if there are active contacts on it?

2023-11-02 23:36 UTC, asdfryan commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +  test.skip(`Error body`, async () => {
are we intentionally skipping?

2023-11-03 17:23 UTC, asdfryan approved these changes

2023-11-03 20:39 UTC, tonyxiao commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +      addedObjects.push({
![image](https://github.com/supaglue-labs/supaglue/assets/696842/8b33761b-674e-495e-b73c-4ca522d27466)
Yes, it appears so.

2023-11-03 20:42 UTC, tonyxiao commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +      addedObjects.push({
Though delete is only supported in outreach api though.

2023-11-03 20:42 UTC, merged

2023-11-03 20:44 UTC, tonyxiao commented on apps/api/routes/engagement/v2/sequence.integration.test.ts
> +      addedObjects.push({
![image](https://github.com/supaglue-labs/supaglue/assets/696842/e3235934-808e-4164-a4ed-83d99fb5ed99)


And for apollo I don't think there is delete at all, only archive.