feat: SDK from generated openapi types and start using it in integration tests
supaglue-labs/supaglue pull request #1861
Opened 2023-11-04 01:19 UTC by tonyxiao

Additionally adding ability to inspect requests made in integration tests via proxy

2023-11-04 01:25 UTC, tonyxiao commented
Is anyone familiar with this issue? 
![image](https://github.com/supaglue-labs/supaglue/assets/696842/0979af22-7066-4dfa-a94b-bbb39da5203b)

2023-11-07 18:00 UTC, lucasmarshall requested changes

2023-11-07 18:00 UTC, lucasmarshall commented on packages/schemas/supaglue-client.ts
> +    ['marketing-automation']: createClient<marketingAutomation>(getOptions('marketing/v2-automation')),
```suggestion
    ['marketing-automation']: createClient<marketingAutomation>(getOptions('marketing-automation/v2')),
```

2023-11-07 18:53 UTC, tonyxiao commented on packages/schemas/supaglue-client.ts
> +    ['marketing-automation']: createClient<marketingAutomation>(getOptions('marketing/v2-automation')),
I was trying to make it correspond 1-1 with the API as much as possible. sounds good though will make the change.

2023-11-07 18:55 UTC, tonyxiao commented on packages/schemas/supaglue-client.ts
> +  providerName?: string;
The intention was to have it optional here you can either have it once for the whole client or still have the option to pass in per-request (which is the current state). Because depending on the context you may need to call it for the same customer over and over again, for example in our integration tests.

2023-11-07 18:56 UTC, tonyxiao commented on packages/schemas/supaglue-client.ts
> +  providerName?: string;
Happy to remove it for now though as two ways of doing things could also be confusing.

2023-11-08 07:40 UTC, supaglue-user commented
ok ready for review again.

2023-11-09 00:09 UTC, tonyxiao commented
@lucasmarshall ready for another look

2023-11-09 21:34 UTC, lucasmarshall approved these changes

2023-11-09 23:03 UTC, merged