feat: add crm oauth connectors
supaglue-labs/supaglue pull request #190
Opened 2023-03-02 22:23 UTC by tomkit

- add crm connectors for oauth
- seed all of them until we have mgmt apis
- add connector docs, status, feature table

2023-03-02 22:44 UTC, lucasmarshall requested changes

2023-03-02 22:44 UTC, lucasmarshall commented on docs/docusaurus.config.js
> +                href: '/connectors/ms_dynamics_365_sales',
Can we generate this from the files in the directly instead of configuring manually?

2023-03-02 22:44 UTC, lucasmarshall commented on packages/db/prisma/seed.ts
> +  DEV_ZENDESK_SELL_CLIENT_ID,
You need to update the list above.

2023-03-02 23:17 UTC, albertyfwu commented on packages/core/remotes/crm/zendesk_sell/index.ts
> +  public async refreshAccessToken(): Promise<{
don't need these methods

2023-03-02 23:45 UTC, tomkit commented on packages/db/prisma/seed.ts
> +  DEV_ZENDESK_SELL_CLIENT_ID,
Can you say more (from the merge)?

2023-03-02 23:49 UTC, tomkit commented on docs/docusaurus.config.js
> +                href: '/connectors/ms_dynamics_365_sales',
Can we punt on this for when we do more later ?

2023-03-02 23:53 UTC, lucasmarshall commented on docs/docusaurus.config.js
> +                href: '/connectors/ms_dynamics_365_sales',
Sure

2023-03-02 23:54 UTC, lucasmarshall commented on packages/db/prisma/seed.ts
> +  DEV_ZENDESK_SELL_CLIENT_ID,
Line 4:
```
const SUPPORTED_CRM_CONNECTIONS = ['salesforce', 'hubspot', 'pipedrive'];
```

2023-03-03 00:09 UTC, albertyfwu approved these changes

2023-03-03 01:01 UTC, merged