fix: add api key API and middleware guards
supaglue-labs/supaglue pull request #264
Opened 2023-03-13 22:33 UTC by tomkit

- add endpoints to generate and revoke an api key
- add middleware to guard crm endpoints with it
- also fix some incorrect openapi examples

NOTE:
- we need to add a username/password guard for mgmt endpoints for API or Management Portal access

2023-03-13 22:45 UTC, albertyfwu commented on apps/api/routes/mgmt/v1/application/index.ts
> +  applicationRouter.post('/:application_id/_generate_api_key', async (req: Request, res: Response) => {
can we use the actual req and res types?

2023-03-13 22:45 UTC, albertyfwu commented on packages/core/types/application.ts
> +  webhook?: WebhookConfig | null;
what is the reasoning for both `undefined` and `null`? same question for `apiKey`

2023-03-14 00:35 UTC, asdfryan commented on apps/api/routes/mgmt/v1/application/index.ts
> +      const hashedApiKey = await crypto.scryptSync(apiKey, SUPAGLUE_API_KEY_SALT!, 64).toString('hex'); // TODO: remove bang by getting NodeJs ProcessEnv global interface working
We should move encryption stuff into a common lib (shared with our credentials encryption)

2023-03-14 18:55 UTC, asdfryan commented on apps/api/routes/mgmt/v1/application/index.ts
> +      const hashedApiKey = await crypto.scryptSync(apiKey, SUPAGLUE_API_KEY_SALT!, 64).toString('hex'); // TODO: remove bang by getting NodeJs ProcessEnv global interface working
Can move to `lib/crypt.ts`

2023-03-14 18:58 UTC, tomkit commented on apps/api/routes/mgmt/v1/application/index.ts
> +      const hashedApiKey = await crypto.scryptSync(apiKey, SUPAGLUE_API_KEY_SALT!, 64).toString('hex'); // TODO: remove bang by getting NodeJs ProcessEnv global interface working
Let's do as another PR? We should also consolidate the secret keys

2023-03-14 19:02 UTC, asdfryan commented on openapi/mgmt/components/schemas/objects/application_api_key.yaml
> +type: object
We should add the required api key header too

2023-03-14 19:33 UTC, lucasmarshall requested changes

2023-03-14 20:35 UTC, asdfryan commented on .env.sample
> +SUPAGLUE_QUICKSTART_API_KEY="8o2kGDTHwTY6zcQV8gx7ep8vV7F2JNdeu95OR75MY7dlQJhzOiM4Ha/dKwXOTfDzDxVo+a6tZBrVxYfzJFIrgw=="
I think the quotes are unnecessary

2023-03-14 20:35 UTC, tomkit commented on docker-compose.yml
> +      - SUPAGLUE_API_KEY_SALT
I consolidated into SUPAGLUE_API_ENCRYPTION_SECRET

2023-03-14 20:36 UTC, asdfryan approved these changes

2023-03-14 20:36 UTC, lucasmarshall commented on docker-compose.yml
> +      - SUPAGLUE_API_KEY_SALT
Not sure what you mean?

2023-03-14 20:37 UTC, tomkit commented
landing, then we can make additional changes later

2023-03-14 20:37 UTC, merged