fix: implement initial version of next-auth
supaglue-labs/supaglue pull request #275
Opened 2023-03-14 23:47 UTC by tomkit

2023-03-14 23:49 UTC, asdfryan commented on apps/api/routes/internal/v1/index.ts
> +  v1Auth(app);
This should also be guarded by the internal middleware

2023-03-14 23:49 UTC, asdfryan commented on apps/mgmt-ui/src/components/AccountMenu/index.tsx
> +        {/* <MenuItem onClick={handleClose}>
Why not just delete?

2023-03-14 23:49 UTC, asdfryan commented on apps/mgmt-ui/src/hooks/useCustomers.ts
>    const { data, error, isLoading } = useSWR(`${API_HOST}/mgmt/v1/applications/${APPLICATION_ID}/customers`, fetcher);
This should be using internal

2023-03-14 23:54 UTC, asdfryan commented on packages/db/prisma/schema.prisma
> +  SgUser      SgUser[]
This doesn't feel right -- the way this relation is defined, a single Application can have multiple SgUsers?

2023-03-14 23:54 UTC, asdfryan commented on apps/mgmt-ui/package.json
> +    "@next-auth/prisma-adapter": "^1.0.5",
Do we need this?

2023-03-15 02:33 UTC, tomkit commented on packages/db/prisma/schema.prisma
> +  SgUser      SgUser[]
I think we eventually want many-many. For now, I think we’ll have more users invited to the same application since we don’t allow creation of Applications

2023-03-15 02:34 UTC, tomkit commented on apps/api/routes/internal/v1/index.ts
> +  v1Auth(app);
+1

2023-03-15 02:34 UTC, tomkit commented on apps/mgmt-ui/src/hooks/useCustomers.ts
>    const { data, error, isLoading } = useSWR(`${API_HOST}/mgmt/v1/applications/${APPLICATION_ID}/customers`, fetcher);
+1

2023-03-15 02:34 UTC, tomkit commented on apps/mgmt-ui/src/components/AccountMenu/index.tsx
> +        {/* <MenuItem onClick={handleClose}>
+1

2023-03-15 02:34 UTC, tomkit commented on packages/db/prisma/schema.prisma
> +  SgUser      SgUser[]
I think we eventually want many-many. For now, I think we’ll have more users invited to the same application since we don’t allow creation of Applications

2023-03-15 02:35 UTC, tomkit commented on apps/mgmt-ui/package.json
> +    "@next-auth/prisma-adapter": "^1.0.5",
Removed

2023-03-15 02:36 UTC, tomkit commented on apps/mgmt-ui/src/components/AccountMenu/index.tsx
> +        {/* <MenuItem onClick={handleClose}>
+1

2023-03-15 17:35 UTC, lucasmarshall requested changes

2023-03-15 17:35 UTC, lucasmarshall commented on apps/mgmt-ui/.env.sample
> +NEXT_PUBLIC_SUPAGLUE_INTERNAL_TOKEN=
We can't have this in the FE or we'll have to build a docker image per customer with their shared secret baked in.

2023-03-15 17:36 UTC, lucasmarshall commented on apps/mgmt-ui/.env.sample
> +NEXT_PUBLIC_SUPAGLUE_INTERNAL_TOKEN=
We need all api access proxied through the edge so we can inject this.

2023-03-15 18:01 UTC, lucasmarshall commented on apps/mgmt-ui/src/pages/api/auth/[...nextauth].ts
> +const sgInternalToken = process.env.SUPAGLUE_INTERNAL_TOKEN!;
This isn't being set in the next app

2023-03-15 18:06 UTC, tomkit commented on apps/mgmt-ui/.env.sample
> +NEXT_PUBLIC_SUPAGLUE_INTERNAL_TOKEN=
I fixed this

2023-03-15 18:06 UTC, tomkit commented on apps/mgmt-ui/src/pages/api/auth/[...nextauth].ts
> +const sgInternalToken = process.env.SUPAGLUE_INTERNAL_TOKEN!;
Fixed in the last commit

2023-03-15 18:16 UTC, lucasmarshall approved these changes

2023-03-15 18:17 UTC, merged