docs: clean up docs
supaglue-labs/supaglue pull request #47
Opened 2023-02-03 23:39 UTC by asdfryan

2023-02-03 23:49 UTC, lucasmarshall requested changes

2023-02-03 23:49 UTC, lucasmarshall commented on docs/versioned_docs/version-0.1.x/tutorial.md
> +1. `cd` into `/apps/sample-app` if you are not already there and start the sample app locally:
Can we make the cd command a code block and change the path to `apps/sample-app`?

2023-02-03 23:49 UTC, lucasmarshall commented on docs/versioned_docs/version-0.1.x/tutorial.md
> +1. Create `account.ts` inside the `/apps/sample-app/supaglue-config` directory. Paste in the following:
```suggestion
1. Create `account.ts` inside the `apps/sample-app/supaglue-config` directory. Paste in the following:
```

2023-02-04 00:10 UTC, george-xing approved these changes

2023-02-04 00:10 UTC, merged