fix: openapi tags for sequence states
supaglue-labs/supaglue pull request #829
Opened 2023-05-12 20:40 UTC by asdfryan

2023-05-12 20:42 UTC, albertyfwu requested changes
i think you also need to update tag for singular `SequenceState`

2023-05-12 20:42 UTC, albertyfwu commented
<img width="450" alt="image" src="https://github.com/supaglue-labs/supaglue/assets/1498227/6ad3e052-a06d-45f5-ad2a-97417a6cdbae">

2023-05-12 21:07 UTC, asdfryan commented
> 

done

2023-05-15 17:03 UTC, albertyfwu approved these changes

2023-05-15 17:04 UTC, lucasmarshall approved these changes

2023-05-15 17:05 UTC, merged